language: go
os:
  - osx

osx_image: xcode10

before_install:
  - brew install git-lfs
  - git lfs install --system
  - git lfs pull

sudo: false

go:
  - 1.9
  - 1.10
  - 1.11
  - tip

script:
  - go test -v ./...
